name: Build and Push Docker Image

on:
  push:
    branches:
      - develop_devops  # Change to the branch you want to trigger the build

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and tag the Docker image
        run: |
          docker build -t evgeniygordeev/vpn-project:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push evgeniygordeev/vpn-project:latest
